import Head from 'next/head';

const EventsPage = () => {
  return (
    <>
      {/* <Head>
        <title>Events</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <h2>EventsPage</h2>
    </>
  );
};

export default EventsPage;
